application: sentagstream
version: 1
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /tag
  script: tagpost.py

- url: /follow
  script: addfollowers.py

- url: /stream
  script: getpost.py

- url: /get
  script: getpost.py
